### ISSUE TITLE
Item images

### ISSUE THREAD

**Issue by Johnny112233** [Jerry1211/PUBG-Radar-master#1]
Are images of the ressources folder already showable?

**Comment by Jerry1211** [comment]
yes
`    iconImages = mapOf(
      "AR.Supp" to Texture(Gdx.files.internal("icons/AR.Supp.png")),
      "S.Supp" to Texture(Gdx.files.internal("icons/S.Supp.png")),
      "AR.Comp" to Texture(Gdx.files.internal("icons/AR.Comp.png")),
      "S.Comp" to Texture(Gdx.files.internal("icons/S.Comp.png")),
      "AR.ExtQ" to Texture(Gdx.files.internal("icons/AR.ExtQ.png")),
      "S.ExtQ" to Texture(Gdx.files.internal("icons/S.ExtQ.png")),
      "AR.Ext" to Texture(Gdx.files.internal("icons/AR.Ext.png")),
      "S.Ext" to Texture(Gdx.files.internal("icons/S.Ext.png")),
      "AR.Stock" to Texture(Gdx.files.internal("icons/AR.Stock.png")),
      "CheekPad" to Texture(Gdx.files.internal("icons/CheekPad.png")),
      "A.Grip" to Texture(Gdx.files.internal("icons/A.Grip.png")),
      "V.Grip" to Texture(Gdx.files.internal("icons/V.Grip.png")),
      "556" to Texture(Gdx.files.internal("icons/556.png")),
      "98k" to Texture(Gdx.files.internal("icons/98k.png")),
      "Mini" to Texture(Gdx.files.internal("icons/Mini.png")),
      "m416" to Texture(Gdx.files.internal("icons/M4.png")),
      "Scar" to Texture(Gdx.files.internal("icons/Scar.png")),
      "Ak" to Texture(Gdx.files.internal("icons/Ak.png")),
      "8x" to Texture(Gdx.files.internal("icons/8x.png")),
      "4x" to Texture(Gdx.files.internal("icons/4x.png")),
      "2x" to Texture(Gdx.files.internal("icons/2x.png")),
      "R.Dot" to Texture(Gdx.files.internal("icons/R.Dot.png")),
      "armor3" to Texture(Gdx.files.internal("icons/Arm3.png")),
      "armor2" to Texture(Gdx.files.internal("icons/Arm2.png")),
      "helmet3" to Texture(Gdx.files.internal("icons/Helm3.png")),
      "helmet2" to Texture(Gdx.files.internal("icons/Helm2.png")),
      "Bag3" to Texture(Gdx.files.internal("icons/Bag3.png")),
      "Bag2" to Texture(Gdx.files.internal("icons/Bag2.png")),
      "Pan" to Texture(Gdx.files.internal("icons/Pan.png")),
      "MedKit" to Texture(Gdx.files.internal("icons/MedKit.png")),
      "FirstAid" to Texture(Gdx.files.internal("icons/FirstAid.png")),
      "Pain" to Texture(Gdx.files.internal("icons/Pain.png")),
      "Drink" to Texture(Gdx.files.internal("icons/Drink.png")),
      "Grenade" to Texture(Gdx.files.internal("icons/Grenade.png"))
    )`

Remove item from Drawblacklist to make them draw

`var itemNameDrawBlacklist = arrayListOf(
        "AR.Stock",
        "S.Loops",
        "S.Comp",
        "U.Supp",
        "Choke",
        "V.Grip",
        "A.Grip",
        "556",
        "762",
        "Ak",
        "U.Ext",
        "AR.Ext",
        "2x",
        "Mini",
        "Vector",
        "Grenade"
      )`

**Comment by FrZ-BR** [comment]
@Jerry1211 do you have any idea how this can be done with java?
![screenshot_1](https://user-images.githubusercontent.com/17305867/36393783-d70ee49c-158f-11e8-801b-d81c80b4b3ce.png)

im following all your changes and i must say. great work.

**Comment by Jerry1211** [comment]
Let me Test this build and commit these changes one sec

**Comment by Jerry1211** [comment]
@FrZ-BR Instead of Drawing the Cross i can just input the sprite as an image and put the item name above it.

**Comment by FrZ-BR** [comment]
@Jerry1211 Just test it. awesome just like i imagine... the sprite option would be good too..

nice concept

**Comment by Jerry1211** [comment]
Easyer to just edit the icons
![java_2018-02-20_14-25-50](https://user-images.githubusercontent.com/36603302/36406361-4c23c8b4-164a-11e8-83ed-e16dac80ae70.png)
![java_2018-02-20_14-26-00](https://user-images.githubusercontent.com/36603302/36406362-4c522538-164a-11e8-912c-b79b43738f59.png)
![java_2018-02-20_14-26-12](https://user-images.githubusercontent.com/36603302/36406363-4c8084dc-164a-11e8-81c4-46af8070c562.png)

**Comment by FrZ-BR** [comment]
Great work @Jerry1211 

I wanted to have this knowledge in java so I could make these changes myself, but I'm learning a lot from your version thank you !

i will try later to replace the vehicles (squares) for some png with transparency.

**Comment by Jerry1211** [comment]
@FrZ-BR I too am learning as i go on, i know LIttle Java from what i learnt @ Uni.

My To-Do
1. Replace all Weapons Icons w/ Names
2. Replace Drawn Square for Airdrop
3. Replace Yellow Square for Dead Body/Crate with a Image.
4. Replace Drawn Rectangles for Vehicles With Images,

**Comment by Jerry1211** [comment]
@FrZ-BR Hey if you could, try and get the corpse and airdrops to draw with my new commit.

**Comment by FrZ-BR** [comment]
@Jerry1211 I was going to tell you this ... but there are developers that do not like it very much ... coming home in a few hours I'll do in photoshop ... what extension? png with transparecy?

**Comment by Jerry1211** [comment]
@FrZ-BR nah I've done all that I've just gotta figure out how to draw the texture I'll figure it out later I guess

**Comment by FrZ-BR** [comment]
@Jerry1211 i saw wrong... i will be at home soon will try to implement the draw

**Comment by Jerry1211** [comment]
@FrZ-BR when some one dies it goes all white give it a go. uncomment drawcorpes2()
