### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ljw019011** [Jerry1211/PUBG-Radar-master#9]
![image](https://user-images.githubusercontent.com/36692184/36469822-e3f94920-172b-11e8-92fe-a23cf98d4a2f.png)

![image](https://user-images.githubusercontent.com/36692184/36469582-0c659d74-172b-11e8-8abc-e0abd270ebe2.png)

please help me this on this error

**Comment by konetele** [comment]
Java jdk installed?

**Comment by ljw019011** [comment]
@konetele yse I installed JDK 1.8.0_161 and I added JAVA_HOME too

**Comment by Jerry1211** [comment]
Install JRE1.8 161
